apiVersion: v1
kind: Pod
metadata:
  name: env-echgo
  labels:
    app: env-echgo
  namespace: default
spec:
  # nodeName: ip-10-102-219-72.ec2.internal
  containers:
  - image: ghcr.io/tolson-vkn/env-echgo:latest
    imagePullPolicy: Always
    name: env-echgo
    env:
    - name: ECHGO_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: ECHGO_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: ECHGO_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  restartPolicy: Always
