apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: 
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  name: env-echgo-ing
  namespace: env-echgo
spec:
  ingressClassName: nginx
  rules:
    - host: envechgo.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: env-echgo
                port:
                  number: 8080
  # tls:
  #   - hosts:
  #       - envechgo.example.com
  #     secretName: tls-secret

